### ISSUE TITLE
About input of two networks

### ISSUE THREAD

**Issue by jerrywyn** [VITA-Group/SSHarmonization#17]
Hello.
In the supplementary material, I would like to ask why the input channel of the content network is 4 , is it adding mask in addition to the picture input of three channels? If so, why the input channel of reference network is three channels without mask channel?
![图片](https://user-images.githubusercontent.com/48412363/187074423-f26262a2-46bc-4b9e-9c7c-c278612a93ed.png)

**Comment by yifanjiang97** [comment]
Sorry about that typos. It should be 3 in stead of 4!

**Comment by jerrywyn** [comment]
这是来自QQ邮箱的假期自动回复邮件。
